################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/%.o drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/%.su drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/%.cyclo: ../drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/%.c drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DDEBUG -DSTM32 -DSTM32F429ZITx -DSTM32F4 -c -I../Inc -I"/Users/deepg/STM32CubeIDE/workspace_2.1.1/flappy_bird/drivers/Drivers/BSP/STM32F429I-Discovery" -I"/Users/deepg/STM32CubeIDE/workspace_2.1.1/flappy_bird/drivers/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/deepg/STM32CubeIDE/workspace_2.1.1/flappy_bird/Inc" -I"/Users/deepg/STM32CubeIDE/workspace_2.1.1/flappy_bird/drivers/Drivers/CMSIS" -I"/Users/deepg/STM32CubeIDE/workspace_2.1.1/flappy_bird/drivers/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/deepg/STM32CubeIDE/workspace_2.1.1/flappy_bird/drivers/Drivers/CMSIS/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-drivers-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions

clean-drivers-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f64.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f64.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f64.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o
	-$(RM) ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.su ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o ./drivers/Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-drivers-2f-Drivers-2f-CMSIS-2f-DSP-2f-Source-2f-FilteringFunctions

